apiVersion: v1
kind: Pod
metadata:
  name: multitool
spec:
  containers:
  - name: network-multitool
    image: praqma/network-multitool
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        cpu: "50m"
        memory: "50Mi"
